spring:
 datasource:
   driverClassName: org.h2.Driver
   jdbc-url: jdbc:h2:file:~/dasboot
   username: sa
   password:

# file based h2 is used so that ur DB changes are retrieved post application refresh


 h2:
    console:
      enabled: true
      path: /h2

spring.jpa.hibernate.ddl-auto: none
spring.flyway.baselineOnMigrate: true
